Stripe api setup
hatchways/team-wintergreen pull request #67
Opened 2022-02-07 23:51 UTC by panwaramita

### What this PR does (required):
- Set Up a developer account.
- Get the secret key and add it to the .env file.
- create a controller and route for:
- creating customer
- update customer
- retrieve customer
- retrieve customer
- create a checkout session

close #40

2022-02-08 16:05 UTC, ezeilo-su requested changes
Hey @panwaramita, use the correct linters setup and format your code. Let's get this done to tidy up our code.
Happy coding!

2022-02-09 13:57 UTC, panwaramita commented on server/controllers/stripe.js
> +            customer: customer,
Done the changes

2022-02-09 21:34 UTC, ezeilo-su reviewed
Thank you for the requested changes.

2022-02-10 22:56 UTC, rajivtitus commented on server/app.js
> +>>>>>>> 4d697bc7232c3803f506e6ae2286e1cd28974508
Let's remove these commit hashes

Ditto throughout

2022-02-10 22:58 UTC, rajivtitus approved these changes
Good start with the routes. We'll have to refactor them to fit our use cases, we can do that in the subsequent payment related tickets 👍🏽  

Just a comment to address before merging

2022-02-10 23:53 UTC, merged